const CreateProcess = Object.freeze({
  TOPIC: 'TOPIC',
  WRITER_INTERFACE: 'WRITER_INTERFACE'
});

const Status = Object.freeze({
  WAITING_FOR_WRITER: 'WAITING_FOR_WRITER',
  ASSIGNED_TO_WRITER: 'ASSIGNED_TO_WRITER',
  WRITING_INPROGRESS: 'WRITING_INPROGRESS',
  WRITING_COMPLETE: 'WRITING_COMPLETE',
  ASSIDNED_TO_EDITOR: 'ASSIDNED_TO_EDITOR',
  EDITING_IN_PROGRESS: 'EDITING_IN_PROGRESS',
  EDITING_COMPLETE: 'EDITING_COMPLETE'
});

module.exports = {
  CreateProcess,
  Status
};
