const {
  PRODUCT_CONTENT_API_MONGO_URL,
  GCP_CREDENTIALS_PATH,
  GOOGLE_APPLICATION_CREDENTIALS,
  DEFAULT_MS_GRAPH_SCOPE,
  MS_GRAPH_HOST_NAME,
  MS_LOGIN_HOST_NAME,
  POST_LOGOUT_REDIRECT_URI,
  PRODUCT_CONTENT_API_MONGO_USR,
  PRODUCT_CONTENT_API_MONGO_PWD,
  PRODUCT_CONTENT_API_TENANT_ID,
  PRODUCT_CONTENT_API_CLIENT_ID,
  PRODUCT_CONTENT_API_WRITERS_GROUP_ID,
  PRODUCT_CONTENT_API_EDITOR_GROUP_ID,
  PRODUCT_CONTENT_API_CLIENT_SECRET,
  MONGODB_DATABASE_URL,
  POSTGRES_DATABASE_URL
} = process.env;

const properties = {
  CLIENT_SECRET: PRODUCT_CONTENT_API_CLIENT_SECRET,
  CLIENT_ID: PRODUCT_CONTENT_API_CLIENT_ID,
  DEFAULT_MS_GRAPH_SCOPE,
  MS_LOGIN_HOST_NAME,
  MONGODB_DATABASE_URL,
  POSTGRES_DATABASE_URL,
  TENANT_ID: PRODUCT_CONTENT_API_TENANT_ID,
  MS_GRAPH_HOST_NAME,
  WRITERS_GROUP_ID: PRODUCT_CONTENT_API_WRITERS_GROUP_ID,
  EDITOR_GROUP_ID: PRODUCT_CONTENT_API_EDITOR_GROUP_ID
};

console.log(`Environment variables`);
console.log(process.env);

module.exports = {
  properties
};
