const {
  DEFAULT_MS_GRAPH_SCOPE,
  MS_GRAPH_HOST_NAME,
  MS_LOGIN_HOST_NAME,
  ATTRIBUTE_API_DOMAIN_NAME,
  COPY_API_DOMAIN_NAME,
  MERCH_API_DOMAIN_NAME,
  PRODUCT_CONTENT_API_TENANT_ID,
  PRODUCT_CONTENT_API_CLIENT_ID,
  PRODUCT_CONTENT_API_WRITERS_GROUP_ID,
  PRODUCT_CONTENT_API_WRITER_GROUP_NAME,
  PRODUCT_CONTENT_API_ADMIN_GROUP_ID,
  PRODUCT_CONTENT_API_ADMIN_GROUP_NAME,
  PRODUCT_CONTENT_API_EDITOR_GROUP_ID,
  PRODUCT_CONTENT_API_EDITOR_GROUP_NAME,
  PRODUCT_CONTENT_API_SIZING_GROUP_ID,
  PRODUCT_CONTENT_API_SIZING_GROUP_NAME,
  PRODUCT_CONTENT_API_CLIENT_SECRET,
  MONGODB_DATABASE_URL,
  NETSUITE_PUBSUB_TOPIC,
  POSTGRES_DATABASE_URL,
  USER_EMAIL,
  USER_NAME
} = process.env;

const properties = {
  CLIENT_SECRET: PRODUCT_CONTENT_API_CLIENT_SECRET,
  CLIENT_ID: PRODUCT_CONTENT_API_CLIENT_ID,
  DEFAULT_MS_GRAPH_SCOPE,
  MS_LOGIN_HOST_NAME,
  MONGODB_DATABASE_URL,
  POSTGRES_DATABASE_URL,
  TENANT_ID: PRODUCT_CONTENT_API_TENANT_ID,
  MS_GRAPH_HOST_NAME,
  ATTRIBUTE_API_DOMAIN_NAME,
  COPY_API_DOMAIN_NAME,
  MERCH_API_DOMAIN_NAME,
  NETSUITE_PUBSUB_TOPIC,
  ADMIN_GROUP_ID: PRODUCT_CONTENT_API_ADMIN_GROUP_ID,
  WRITERS_GROUP_ID: PRODUCT_CONTENT_API_WRITERS_GROUP_ID,
  EDITOR_GROUP_ID: PRODUCT_CONTENT_API_EDITOR_GROUP_ID
};

const groups = {
  ADMIN_GROUP_ID: PRODUCT_CONTENT_API_ADMIN_GROUP_ID,
  ADMIN_GROUP_NAME: PRODUCT_CONTENT_API_ADMIN_GROUP_NAME,
  WRITER_GROUP_ID: PRODUCT_CONTENT_API_WRITERS_GROUP_ID,
  WRITER_GROUP_NAME: PRODUCT_CONTENT_API_WRITER_GROUP_NAME,
  EDITOR_GROUP_ID: PRODUCT_CONTENT_API_EDITOR_GROUP_ID,
  EDITOR_GROUP_NAME: PRODUCT_CONTENT_API_EDITOR_GROUP_NAME,
  SIZING_GROUP_ID: PRODUCT_CONTENT_API_SIZING_GROUP_ID,
  SIZING_GROUP_NAME: PRODUCT_CONTENT_API_SIZING_GROUP_NAME
};

const dummyAuth = {
  username: USER_NAME,
  email: USER_EMAIL
};

module.exports = {
  properties,
  groups,
  dummyAuth
};
